/**
 * Sample submittal data for demonstration purposes.
 * In a production application, this would be stored in a database.
 * 
 * CSI Division codes:
 * - Division 22: Plumbing
 * - Division 26: Electrical
 * - Division 08: Openings
 * - Division 09: Finishes
 * - Division 23: HVAC
 */

const submittals = [
  {
    id: 'sub-001',
    projectName: 'Downtown Office Building',
    csiDivision: '22',
    csiSection: '22 40 00',
    sectionTitle: 'Plumbing Fixtures',
    productCategory: 'Water Closets',
    productName: 'Kohler Wellworth Two-Piece Toilet',
    manufacturer: 'Kohler',
    modelNumber: 'K-3999-0',
    description: 'Two-piece elongated toilet with 1.28 gpf flush',
    status: 'approved',
    approvalDate: '2024-03-15',
    location: 'Floors 1-10, Restrooms',
    keywords: ['toilet', 'water closet', 'bathroom', 'restroom', 'wc', 'commode'],
    documentUrl: '/documents/submittals/22-40-00-001.pdf'
  },
  {
    id: 'sub-002',
    projectName: 'Downtown Office Building',
    csiDivision: '22',
    csiSection: '22 40 00',
    sectionTitle: 'Plumbing Fixtures',
    productCategory: 'Lavatories',
    productName: 'American Standard Lucerne Wall-Mount Sink',
    manufacturer: 'American Standard',
    modelNumber: '0356.421.020',
    description: 'Wall-mounted lavatory sink with overflow',
    status: 'approved',
    approvalDate: '2024-03-16',
    location: 'Floors 1-10, Restrooms',
    keywords: ['sink', 'lavatory', 'bathroom', 'restroom', 'basin', 'wash basin'],
    documentUrl: '/documents/submittals/22-40-00-002.pdf'
  },
  {
    id: 'sub-003',
    projectName: 'Downtown Office Building',
    csiDivision: '22',
    csiSection: '22 40 00',
    sectionTitle: 'Plumbing Fixtures',
    productCategory: 'Urinals',
    productName: 'Sloan WES-1000 Waterfree Urinal',
    manufacturer: 'Sloan',
    modelNumber: 'WES-1000',
    description: 'Waterfree urinal with EcoLogic cartridge',
    status: 'approved',
    approvalDate: '2024-03-17',
    location: 'Floors 1-10, Mens Restrooms',
    keywords: ['urinal', 'bathroom', 'restroom', 'mens room'],
    documentUrl: '/documents/submittals/22-40-00-003.pdf'
  },
  {
    id: 'sub-004',
    projectName: 'Downtown Office Building',
    csiDivision: '26',
    csiSection: '26 50 00',
    sectionTitle: 'Lighting',
    productCategory: 'LED Fixtures',
    productName: 'Lithonia IBL LED High Bay',
    manufacturer: 'Lithonia Lighting',
    modelNumber: 'IBL-24L-50K',
    description: '24,000 lumen LED high bay fixture, 5000K',
    status: 'approved',
    approvalDate: '2024-02-20',
    location: 'Parking Garage Levels P1-P3',
    keywords: ['light', 'lighting', 'high bay', 'led', 'fixture', 'parking'],
    documentUrl: '/documents/submittals/26-50-00-001.pdf'
  },
  {
    id: 'sub-005',
    projectName: 'Downtown Office Building',
    csiDivision: '26',
    csiSection: '26 50 00',
    sectionTitle: 'Lighting',
    productCategory: 'Troffer Fixtures',
    productName: 'Philips Ledalite 2x4 LED Troffer',
    manufacturer: 'Philips',
    modelNumber: '2FLT4-LED-40L-835',
    description: '2x4 LED troffer, 4000 lumens, 3500K',
    status: 'approved',
    approvalDate: '2024-02-22',
    location: 'Floors 1-10, Office Areas',
    keywords: ['light', 'lighting', 'troffer', 'led', 'office', 'ceiling'],
    documentUrl: '/documents/submittals/26-50-00-002.pdf'
  },
  {
    id: 'sub-006',
    projectName: 'Downtown Office Building',
    csiDivision: '08',
    csiSection: '08 11 00',
    sectionTitle: 'Metal Doors and Frames',
    productCategory: 'Hollow Metal Doors',
    productName: 'Ceco Door Hollow Metal Door',
    manufacturer: 'Ceco Door',
    modelNumber: 'HD-18G',
    description: '18 gauge hollow metal door, 3\'0" x 7\'0"',
    status: 'approved',
    approvalDate: '2024-01-15',
    location: 'Throughout Building',
    keywords: ['door', 'metal door', 'hollow metal', 'entry', 'exit'],
    documentUrl: '/documents/submittals/08-11-00-001.pdf'
  },
  {
    id: 'sub-007',
    projectName: 'Downtown Office Building',
    csiDivision: '08',
    csiSection: '08 71 00',
    sectionTitle: 'Door Hardware',
    productCategory: 'Locksets',
    productName: 'Schlage L-Series Mortise Lock',
    manufacturer: 'Schlage',
    modelNumber: 'L9453P',
    description: 'Heavy duty mortise lock, classroom function',
    status: 'approved',
    approvalDate: '2024-01-18',
    location: 'Throughout Building',
    keywords: ['lock', 'lockset', 'door hardware', 'hardware', 'mortise'],
    documentUrl: '/documents/submittals/08-71-00-001.pdf'
  },
  {
    id: 'sub-008',
    projectName: 'Downtown Office Building',
    csiDivision: '09',
    csiSection: '09 51 00',
    sectionTitle: 'Acoustical Ceilings',
    productCategory: 'Ceiling Tiles',
    productName: 'Armstrong Ultima Ceiling Tile',
    manufacturer: 'Armstrong',
    modelNumber: '1912',
    description: '2\'x2\' acoustical ceiling tile, NRC 0.70',
    status: 'approved',
    approvalDate: '2024-04-01',
    location: 'Floors 1-10, Office Areas',
    keywords: ['ceiling', 'ceiling tile', 'acoustical', 'acoustic', 'drop ceiling'],
    documentUrl: '/documents/submittals/09-51-00-001.pdf'
  },
  {
    id: 'sub-009',
    projectName: 'Downtown Office Building',
    csiDivision: '09',
    csiSection: '09 91 00',
    sectionTitle: 'Painting',
    productCategory: 'Interior Paint',
    productName: 'Sherwin-Williams ProMar 200 Interior Latex',
    manufacturer: 'Sherwin-Williams',
    modelNumber: 'B30-W2400',
    description: 'Interior latex paint, eggshell finish, white base',
    status: 'approved',
    approvalDate: '2024-04-10',
    location: 'Throughout Building',
    keywords: ['paint', 'painting', 'interior paint', 'wall paint', 'latex'],
    documentUrl: '/documents/submittals/09-91-00-001.pdf'
  },
  {
    id: 'sub-010',
    projectName: 'Downtown Office Building',
    csiDivision: '23',
    csiSection: '23 05 00',
    sectionTitle: 'HVAC Equipment',
    productCategory: 'Air Handling Units',
    productName: 'Carrier 39M AHU',
    manufacturer: 'Carrier',
    modelNumber: '39M-15',
    description: '15,000 CFM modular air handling unit',
    status: 'approved',
    approvalDate: '2024-02-01',
    location: 'Mechanical Room Level 11',
    keywords: ['ahu', 'air handler', 'hvac', 'air conditioning', 'ac', 'mechanical'],
    documentUrl: '/documents/submittals/23-05-00-001.pdf'
  },
  {
    id: 'sub-011',
    projectName: 'Downtown Office Building',
    csiDivision: '23',
    csiSection: '23 82 00',
    sectionTitle: 'HVAC Accessories',
    productCategory: 'Diffusers',
    productName: 'Titus TDC Square Ceiling Diffuser',
    manufacturer: 'Titus',
    modelNumber: 'TDC-24x24',
    description: '24"x24" square ceiling diffuser, steel',
    status: 'approved',
    approvalDate: '2024-02-05',
    location: 'Floors 1-10, Office Areas',
    keywords: ['diffuser', 'air diffuser', 'hvac', 'vent', 'ceiling vent'],
    documentUrl: '/documents/submittals/23-82-00-001.pdf'
  },
  {
    id: 'sub-012',
    projectName: 'Downtown Office Building',
    csiDivision: '22',
    csiSection: '22 10 00',
    sectionTitle: 'Plumbing Piping',
    productCategory: 'Copper Pipe',
    productName: 'Mueller Copper Tube Type L',
    manufacturer: 'Mueller Industries',
    modelNumber: 'Type L',
    description: 'Type L copper water tube, various sizes',
    status: 'approved',
    approvalDate: '2024-01-10',
    location: 'Throughout Building',
    keywords: ['pipe', 'piping', 'copper', 'water pipe', 'plumbing'],
    documentUrl: '/documents/submittals/22-10-00-001.pdf'
  }
];

module.exports = { submittals };
